### ISSUE TITLE
RxPeripheralImpl.notificationData(...) doesn't work without a preprocessor

### ISSUE THREAD

**Issue by adam-zethraeus** [uber/RxCBCentral#21]
The method will return nil data if a preprocessor isn't set.

https://github.com/uber/RxCBCentral/blob/c7409d40c691df9edd14ea886c454ee06503c3a3/Sources/RxCBCentral/core/RxPeripheralImpl.swift#L267

**Comment by alinekborges** [comment]
Fixed in PR https://github.com/uber/RxCBCentral/pull/25
